services:
  python:
    build:
      context: ./python
    container_name: fastapi-app
    # volumes:
    #   - ./output:/app/src/mnt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8936/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  nginx:
    build:
      context: ./nginx
    container_name: nginx-container
    ports:
      - "5350:80"
