services:
  api:
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "5350:5350"
    volumes:
      - ./output:/app/src/mnt
    # environment:
    #   - DEBUG=1
    #   - API_KEY=${API_KEY}
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # networks:
    #   - app-network
# networks:
#   app-network:
#     driver: bridge
