# Use Python base image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy application code
COPY ./src ./src

# Start the application
CMD ["fastapi", "run", "src/main.py", "--port", "8936"]